declare const Netlify: { env: { get(key: string): string | undefined } };
import { createHmac, timingSafeEqual } from "node:crypto";
const env=(k:string)=>Netlify.env.get(k)||"";
const FALLBACK_KEY="sb_publishable_FX7QKUBZQmwykGcgv8SdfQ_lGRZF8n2";
async function supabasePatch(id:string,payload:Record<string,unknown>){const base=env('SUPABASE_URL').replace(/\/$/,'');const secret=env('SUPABASE_SECRET_KEY');if(!base||!secret)throw new Error('Supabase server environment variables missing');return fetch(`${base}/rest/v1/frankiflow_payments?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{apikey:secret,'content-type':'application/json'},body:JSON.stringify(payload)})}
function validSignature(payload:string,header:string|null,secret:string){if(!header||!secret)return false;const parts=header.split(',').map(x=>x.split('='));const timestamp=parts.find(([k])=>k==='t')?.[1];const signatures=parts.filter(([k])=>k==='v1').map(([,v])=>v);if(!timestamp||!signatures.length)return false;if(Math.abs(Date.now()/1000-Number(timestamp))>300)return false;const expected=createHmac('sha256',secret).update(`${timestamp}.${payload}`,'utf8').digest('hex');const a=Buffer.from(expected,'hex');return signatures.some(sig=>{try{const b=Buffer.from(sig,'hex');return a.length===b.length&&timingSafeEqual(a,b)}catch{return false}})}
async function sendConfirmation(paymentId:string){const base=(env('SUPABASE_URL')||'https://bdeajozhylypiidrldka.supabase.co').replace(/\/$/,'');const key=env('SUPABASE_PUBLISHABLE_KEY')||FALLBACK_KEY;try{const r=await fetch(`${base}/functions/v1/frankiflow-email`,{method:'POST',headers:{apikey:key,'content-type':'application/json'},body:JSON.stringify({event_type:'payment_confirmed',payment_id:paymentId})});if(!r.ok)console.warn('Payment confirmation email failed',await r.text())}catch(e){console.warn('Payment confirmation email failed',e)}}
export default async(req:Request)=>{if(req.method!=='POST')return new Response('Method not allowed',{status:405});const raw=await req.text();if(!validSignature(raw,req.headers.get('stripe-signature'),env('STRIPE_WEBHOOK_SECRET')))return new Response('Invalid signature',{status:400});let event:any;try{event=JSON.parse(raw)}catch{return new Response('Bad payload',{status:400})}const session=event.data?.object;const paymentId=session?.metadata?.frankiflow_payment_id||session?.client_reference_id;let paid=false;if(paymentId&&event.type==='checkout.session.completed'){paid=session.payment_status==='paid';await supabasePatch(paymentId,{status:paid?'paid':'checkout_open',stripe_payment_intent_id:typeof session.payment_intent==='string'?session.payment_intent:null,stripe_customer_id:typeof session.customer==='string'?session.customer:null,paid_at:paid?new Date().toISOString():null,updated_at:new Date().toISOString()})}else if(paymentId&&event.type==='checkout.session.async_payment_succeeded'){paid=true;await supabasePatch(paymentId,{status:'paid',stripe_payment_intent_id:typeof session.payment_intent==='string'?session.payment_intent:null,paid_at:new Date().toISOString(),updated_at:new Date().toISOString()})}else if(paymentId&&event.type==='checkout.session.async_payment_failed'){await supabasePatch(paymentId,{status:'failed',updated_at:new Date().toISOString()})}else if(paymentId&&event.type==='checkout.session.expired'){await supabasePatch(paymentId,{status:'expired',updated_at:new Date().toISOString()})}if(paymentId&&paid)await sendConfirmation(paymentId);return new Response('ok',{status:200})};
export const config={path:"/api/stripe/webhook"};
