import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
const read=p=>readFileSync(p,'utf8');

test('About Us is a homepage accordion only',()=>{assert.equal(existsSync('public/about/index.html'),false);const home=read('public/index.html');const js=read('public/assets/homepage-about-nav.js');assert.match(home,/id="about"/);assert.match(home,/id="aboutAccordion"/);assert.match(home,/href="#about"/);assert.doesNotMatch(home,/href="\/about\/"/);assert.match(js,/slice\(0,3\)/);assert.match(js,/<details class=/);assert.doesNotMatch(js,/padStart|about-page-story-head/)});
test('Accommodations remains the final navigation link after FAQ',()=>{for(const p of ['public/index.html','public/en/index.html']){const s=read(p);const nav=s.match(/<nav[^>]*class="nav-links"[^>]*>([\s\S]*?)<\/nav>/)?.[1]||'';assert.ok(nav.lastIndexOf('Accommodations')>nav.lastIndexOf('FAQ'))}});

test('calculator page loads exactly one primary controller',()=>{const html=read('public/preisrechner/index.html');assert.match(html,/calculator-app-v3\.js\?v=/);assert.doesNotMatch(html,/calculator\.js\?v=/);assert.doesNotMatch(html,/calculator-runtime-fix\.js\?v=/);assert.equal((html.match(/createClient/g)||[]).length,0)});
test('calculator controller wires print, contact and checklist buttons',()=>{const js=read('public/assets/calculator-app-v3.js'),html=read('public/preisrechner/index.html');for(const id of ['printQuote','requestService','viewChecklist','quoteRequestModal','checklistPreview'])assert.match(html,new RegExp(`id="${id}"`));assert.match(js,/addEventListener\('click',\(\)=>printDoc\('quote'\)\)/);assert.match(js,/addEventListener\('click',openServiceRequest\)/);assert.match(js,/addEventListener\('click',toggleChecklist\)/)});
test('contact with quotation sends admin and customer email events',()=>{const js=read('public/assets/calculator-app-v3.js');assert.match(js,/event_type:'admin_enquiry'/);assert.match(js,/attach_quote:true/);assert.match(js,/event_type:'enquiry_received'/);assert.match(js,/frankiflow_quote_requests/)});
test('print includes logo, organisation and founder',()=>{const js=read('public/assets/calculator-app-v3.js');assert.match(js,/frankiflow-logo\.png/);assert.match(js,/FrankiFlow Gebäudereinigung &amp; Objektbetreuung/);assert.match(js,/Inura Devasurendra/);assert.doesNotMatch(js,/FrankiFlow Unternehmensdaten/);assert.match(js,/await waitForImages\(sheet\)/)});
test('admin exposes editable window contract reductions',()=>{assert.match(read('public/admin/index.html'),/id="windowContractGrid"/);const js=read('public/assets/admin-base.js');assert.match(js,/data-window-contract/);assert.match(js,/contract_reduction_pct:windowReductions/)});
test('language switch is handled by the single controller and persists selection',()=>{const js=read('public/assets/calculator-app-v3.js');assert.match(js,/localStorage\.setItem\('frankiflow-lang',lang\)/);assert.match(js,/\.language-switch \[data-lang\]/);assert.match(js,/const prev=n\.value\|\|'yes'/)});
test('calculator has immediate static defaults before remote pricing loads',()=>{const html=read('public/preisrechner/index.html');assert.match(html,/id="frequency"><option value="weekly1">1× pro Woche<\/option>/);assert.match(html,/id="contractMonths"><option value="1">1 Monat<\/option>/)});
test('single controller renders styled summary rows and total per visit',()=>{const js=read('public/assets/calculator-app-v3.js');assert.match(js,/class="breakdown-row"/);assert.match(js,/Gesamt \/ Termin/);assert.match(js,/Total \/ visit/);assert.match(js,/result\.visitTotal/)});
test('window cleaning is a per-visit add-on in engine and UI',()=>{const app=read('public/assets/calculator-app-v3.js'),engine=read('public/assets/calculator-engine.js');assert.match(app,/t\('windowCleaning'\).*visitWord/);assert.match(app,/result\.windowCharge/);assert.match(engine,/floorVisit\+equipmentVisit\+\(s\.windows\?windowCharge:0\)/);assert.match(engine,/monthly=round2\(visitTotal\*visits\)/)});
test('checklist uses database data with built-in fallback and responsive CSS',()=>{const app=read('public/assets/calculator-app-v3.js'),checklists=read('public/assets/checklists.js'),css=read('public/assets/calculator.css');assert.match(app,/frankiflow_checklists/);assert.match(app,/applyChecklistRows/);assert.match(app,/localizeChecklistSections/);assert.match(app,/renderChecklistPreview/);for(const key of ['buero','wohnung','airbnb','treppenhaus','deep','windows'])assert.match(checklists,new RegExp(`\\b${key}:`));assert.match(css,/\.checklist-screen-items/);assert.match(css,/grid-template-columns:repeat\(2/);assert.match(css,/@media\(max-width:700px\)/)});
test('calculator page retains mobile live-price island',()=>{const html=read('public/preisrechner/index.html'),island=read('public/assets/calculator-mobile-island.js');assert.match(html,/calculator-mobile-island\.js\?v=/);assert.match(island,/mobile-price-island/);assert.match(island,/MutationObserver/)});
test('config does not auto-start stale calculator side-effect modules',()=>{const cfg=read('public/assets/config.js');assert.doesNotMatch(cfg,/calculator-overrides|calculator-mobile-island|calculator-header-revert/)});

test('print pagination is iOS-safe and avoids synthetic blank pages',()=>{const css=read('public/assets/calculator.css'),js=read('public/assets/calculator-app-v3.js');assert.match(css,/\.print-sheet\{[^}]*min-height:0!important[^}]*height:auto!important/s);assert.match(css,/\.print-document\{[^}]*height:296mm;min-height:296mm[^}]*overflow:hidden/s);assert.match(css,/\.print-checklist-document\{[^}]*height:296mm;min-height:296mm[^}]*break-before:auto;page-break-before:auto[^}]*overflow:hidden/s);assert.match(css,/\.has-following-print-page\{break-after:page!important;page-break-after:always!important\}/);assert.match(js,/print-document\\\$\{includeChecklist\?' has-following-print-page':''\}/);assert.match(js,/print-checklist-document\\\$\{i<groups\.length-1\?' has-following-print-page':''\}/);});
