import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
const read=p=>readFileSync(p,'utf8');

test('About Us is a homepage accordion only',()=>{assert.equal(existsSync('public/about/index.html'),false);const home=read('public/index.html');const js=read('public/assets/homepage-about-nav.js');assert.match(home,/id="about"/);assert.match(home,/id="aboutAccordion"/);assert.match(home,/href="#about"/);assert.doesNotMatch(home,/href="\/about\/"/);assert.match(js,/slice\(0,3\)/);assert.match(js,/<details class=/);assert.doesNotMatch(js,/padStart|about-page-story-head/)});
test('Accommodations remains the final navigation link after FAQ',()=>{for(const p of ['public/index.html','public/en/index.html']){const s=read(p);const nav=s.match(/<nav[^>]*class="nav-links"[^>]*>([\s\S]*?)<\/nav>/)?.[1]||'';assert.ok(nav.lastIndexOf('Accommodations')>nav.lastIndexOf('FAQ'))}});
test('calculator contact-with-quotation dialog is wired',()=>{const html=read('public/preisrechner/index.html'),js=read('public/assets/calculator.js');assert.match(html,/id="requestService"/);assert.match(html,/id="quoteRequestModal"/);assert.match(js,/event_type:'admin_enquiry'/);assert.match(js,/attach_quote:true/);assert.match(js,/event_type:'enquiry_received'/)});
test('print waits for logo and contains organisation plus founder',()=>{const js=read('public/assets/calculator.js');assert.match(js,/waitForPrintAssets/);assert.match(js,/await waitForPrintAssets\(\)/);assert.match(js,/FrankiFlow Gebäudereinigung &amp; Objektbetreuung/);assert.match(js,/Inura Devasurendra/);assert.doesNotMatch(js,/FrankiFlow Unternehmensdaten/)});
test('admin exposes editable window contract reductions',()=>{assert.match(read('public/admin/index.html'),/id="windowContractGrid"/);const js=read('public/assets/admin-base.js');assert.match(js,/data-window-contract/);assert.match(js,/contract_reduction_pct:windowReductions/)});
test('language switching preserves the new-customer selection',()=>{assert.match(read('public/assets/calculator.js'),/newCustomerValue/)});
test('calculator has immediate static defaults before remote pricing loads',()=>{const html=read('public/preisrechner/index.html');assert.match(html,/id="frequency"><option value="weekly1">1× pro Woche<\/option>/);assert.match(html,/id="contractMonths"><option value="1">1 Monat<\/option>/)});
test('calculator resilient runtime is loaded and repairs summary values',()=>{const html=read('public/preisrechner/index.html'),fix=read('public/assets/calculator-runtime-fix.js');assert.match(html,/calculator-runtime-fix\.js\?v=/);assert.match(html,/calculator\.js\?v=/);assert.match(fix,/calculatePricing\(cfg,state\(\)\)/);assert.match(fix,/visitPrice/);assert.match(fix,/monthlyPrice/);assert.match(fix,/firstMonthPrice/);assert.match(fix,/watchdog/)});
test('config no longer starts stale calculator side-effect modules',()=>{const cfg=read('public/assets/config.js');assert.doesNotMatch(cfg,/calculator-overrides|calculator-mobile-island|calculator-header-revert/)});

test('runtime summary emits styled accessible breakdown rows',()=>{const js=read('public/assets/calculator-runtime-fix.js');assert.match(js,/class="breakdown-row"/);assert.match(js,/#breakdownRows \.breakdown-row/);assert.match(js,/Total \/ visit/);assert.match(js,/Gesamt \/ Termin/)});
test('window cleaning is presented as a per-visit add-on',()=>{const runtime=read('public/assets/calculator-runtime-fix.js'),engine=read('public/assets/calculator-engine.js');assert.match(runtime,/Window cleaning \/ visit/);assert.match(runtime,/Fensterreinigung \/ Termin/);assert.doesNotMatch(runtime,/Window cleaning \/ month/);assert.doesNotMatch(runtime,/Fensterreinigung \/ Monat/);assert.match(engine,/floorVisit\+equipmentVisit\+\(s\.windows\?windowCharge:0\)/);assert.match(engine,/monthly=round2\(visitTotal\*visits\)/)});
test('checklist has resilient rendering plus database and built-in fallback data',()=>{const html=read('public/preisrechner/index.html'),runtime=read('public/assets/calculator-runtime-fix.js'),checklists=read('public/assets/checklists.js');assert.match(html,/id="viewChecklist"/);assert.match(html,/id="checklistPreview"/);assert.match(runtime,/applyChecklistRows/);assert.match(runtime,/localizeChecklistSections/);assert.match(runtime,/frankiflow_checklists/);assert.match(runtime,/bindChecklist/);assert.match(runtime,/stopImmediatePropagation/);assert.match(runtime,/renderChecklist/);for(const key of ['buero','wohnung','airbnb','treppenhaus','deep','windows'])assert.match(checklists,new RegExp(`\\b${key}:`))});
test('checklist runtime has responsive readable UI styles',()=>{const runtime=read('public/assets/calculator-runtime-fix.js');assert.match(runtime,/\.checklist-preview/);assert.match(runtime,/\.checklist-screen-items/);assert.match(runtime,/grid-template-columns:repeat\(2/);assert.match(runtime,/@media\(max-width:720px\)/)});
