alter table public.frankiflow_site_settings
  add column if not exists about_sections jsonb not null default '[]'::jsonb;

update public.frankiflow_site_settings
set
  about_eyebrow = 'Über uns',
  about_title = 'Von einer Idee zu FrankiFlow',
  about_eyebrow_en = 'About Us',
  about_title_en = 'From an Idea to FrankiFlow',
  about_body_1 = 'Hallo, ich bin Inura Devasurendra, Gründer von FrankiFlow. 2019 kam ich nach Deutschland, um meinen Bachelorstudiengang Mobility and Logistics zu absolvieren. Nach meinem Abschluss startete ich meine berufliche Laufbahn als Vehicle Fleet Manager in der Reise- und Transportbranche. Qualitätskontrollen, operative Koordination und die Sicherstellung hoher Servicestandards gehörten dort zu meinem Arbeitsalltag.',
  about_body_2 = 'FrankiFlow verbindet zuverlässigen persönlichen Service mit moderner Technologie. Gemeinsam mit Don Alex Hettiarachi, Software Engineer und Masterstudent in Deutschland, entwickeln wir digitale Lösungen wie den FrankiFlow Preisrechner und bauen das Unternehmen sorgfältig, nachhaltig und Schritt für Schritt weiter auf.',
  about_body_1_en = 'Hi, I’m Inura Devasurendra, founder of FrankiFlow. I came to Germany in 2019 to pursue a bachelor’s degree in Mobility and Logistics. After graduating, I began my professional career as a Vehicle Fleet Manager in the travel and transportation industry, where quality inspections, operational coordination, and maintaining high service standards became an important part of my everyday work.',
  about_body_2_en = 'FrankiFlow combines reliable personal service with modern technology. Together with Don Alex Hettiarachi, a Software Engineer and master’s student in Germany, we develop digital solutions such as the FrankiFlow Price Calculator and continue building the company carefully, sustainably, and step by step.',
  about_sections = $about$[
    {
      "heading_de": "Von einer Idee zu FrankiFlow",
      "heading_en": "From an Idea to FrankiFlow",
      "body_de": "Hallo, ich bin Inura Devasurendra, Gründer von FrankiFlow.\n\n2019 kam ich nach Deutschland, um meinen Bachelorstudiengang Mobility and Logistics zu absolvieren. Nach meinem Abschluss startete ich meine berufliche Laufbahn als Vehicle Fleet Manager in der Reise- und Transportbranche. Qualitätskontrollen, operative Koordination und die Sicherstellung hoher Servicestandards gehörten dort zu meinem Arbeitsalltag.\n\nGleichzeitig hatte ich schon lange den Wunsch, eine eigene Marke aufzubauen. Unternehmertum ist seit jeher Teil meines familiären Hintergrunds, und für mich war klar, dass ich eines Tages etwas schaffen möchte, das nachhaltig wachsen und Menschen einen echten Mehrwert bieten kann.\n\nWährend ich in Frankfurt lebte und arbeitete, bemerkte ich eine starke Nachfrage nach zuverlässigen Dienstleistern. Gleichzeitig hatte ich den Eindruck, dass viele alltägliche Dienstleistungen noch komplizierter, zeitaufwendiger und weniger transparent waren, als sie sein müssten.\n\nDiese Beobachtung wurde zum Ausgangspunkt für FrankiFlow.\n\nDie Idee hinter FrankiFlow ist einfach: alltägliche Dienstleistungen einfacher, transparenter und bequemer zu machen – damit unsere Kundinnen und Kunden eine Sorge weniger haben.",
      "body_en": "Hi, I’m Inura Devasurendra, founder of FrankiFlow.\n\nI came to Germany in 2019 to pursue a bachelor’s degree in Mobility and Logistics. After graduating, I began my professional career as a Vehicle Fleet Manager in the travel and transportation industry, where quality inspections, operational coordination, and maintaining high service standards became an important part of my everyday work.\n\nAt the same time, I had always wanted to build a brand of my own. Entrepreneurship has long been part of my family background, and I knew that one day I wanted to create something that could grow sustainably and deliver real value to people.\n\nWhile living and working in Frankfurt, I noticed strong demand for reliable service providers. At the same time, I felt that many everyday services were still more complicated, time-consuming, and less transparent than they needed to be.\n\nThat observation became the starting point for FrankiFlow.\n\nThe idea behind FrankiFlow is simple: to make everyday services easier, more transparent, and more convenient, giving our customers one less thing to worry about."
    },
    {
      "heading_de": "Wo Service auf Technologie trifft",
      "heading_en": "Where Service Meets Technology",
      "body_de": "FrankiFlow sollte nie einfach nur ein weiteres klassisches Reinigungsunternehmen sein.\n\nVon Anfang an war unser Ziel, zuverlässigen persönlichen Service mit intelligenteren und moderneren Prozessen zu verbinden.\n\nDeshalb haben wir unseren eigenen FrankiFlow Preisrechner entwickelt. Damit erhalten Kundinnen und Kunden schnell und transparent eine erste Preisorientierung – ohne lange Telefonate oder komplizierte Angebotsprozesse.\n\nAn diesem Punkt wurde auch mein Freund Don Alex Hettiarachi zu einem wichtigen Teil der FrankiFlow-Geschichte.\n\nAlex kam für sein Masterstudium nach Deutschland und arbeitet professionell als Software Engineer. Aus einer Idee, die wir gemeinsam besprochen haben, entstand die technische Grundlage des FrankiFlow Preisrechners, den er von Grund auf entwickelt hat.\n\nHeute bauen wir FrankiFlow gemeinsam auf. Ich konzentriere mich vor allem auf Servicequalität, Kundenbeziehungen und operative Abläufe, während Alex seine Erfahrung in Softwareentwicklung, Technologie und digitalen Lösungen einbringt.\n\nDiese Verbindung aus persönlichem Service, Qualitätsmanagement und Technologie ist heute ein wesentlicher Teil dessen, was FrankiFlow besonders macht.",
      "body_en": "FrankiFlow was never intended to be just another traditional cleaning company.\n\nFrom the beginning, our goal has been to combine reliable personal service with smarter and more modern processes.\n\nThat is why we developed our own FrankiFlow Price Calculator, giving customers the possibility to receive a quick and transparent initial price estimate without lengthy phone calls or complicated quotation processes.\n\nThis is also where my friend Don Alex Hettiarachi became an important part of the FrankiFlow story.\n\nAlex came to Germany for his master’s studies and works professionally as a Software Engineer. What began as an idea we discussed together became the technical foundation of the FrankiFlow Price Calculator, which he developed from the ground up.\n\nToday, we are building FrankiFlow together. I focus primarily on service quality, customer relationships, and operational processes, while Alex brings his expertise in software development, technology, and digital solutions.\n\nThis combination of personal service, quality management, and technology has become an important part of what makes FrankiFlow different."
    },
    {
      "heading_de": "Unsere Vision",
      "heading_en": "Our Vision",
      "body_de": "Unser Ziel ist nicht, so schnell wie möglich zu wachsen.\n\nWir möchten sorgfältig, nachhaltig und Schritt für Schritt wachsen.\n\nUnsere Vision ist es, ein zuverlässiges und motiviertes Team aufzubauen, langfristige Beziehungen zu unseren Kunden zu schaffen und die Art, wie unsere Dienstleistungen erbracht werden, kontinuierlich zu verbessern.\n\nDer nächste Schritt ist bereits Teil unserer Reise: eine weitere Niederlassung zu eröffnen und FrankiFlow nach und nach über Frankfurt hinaus auszubauen.\n\nGanz gleich, wie stark FrankiFlow wächst – die Grundsätze hinter dem Unternehmen sollen immer dieselben bleiben:\n\nPersönlicher Kontakt, zuverlässiger Service, Transparenz und Qualität, auf die man sich verlassen kann.\n\nFrankiFlow – Mehr als Reinigung.",
      "body_en": "Our goal is not to grow as quickly as possible.\n\nWe want to grow carefully, sustainably, and step by step.\n\nOur vision is to build a reliable and motivated team, create long-term relationships with our customers, and continuously improve the way our services are delivered.\n\nThe next step is already part of our journey: opening another branch and gradually expanding FrankiFlow beyond Frankfurt.\n\nBut no matter how much FrankiFlow grows, the principles behind the company should always remain the same:\n\nPersonal contact, reliable service, transparency, and quality you can count on.\n\nFrankiFlow – More than cleaning."
    }
  ]$about$::jsonb,
  updated_at = now();

alter table public.frankiflow_site_settings
  alter column about_sections set default $about$[
    {"heading_de":"Von einer Idee zu FrankiFlow","heading_en":"From an Idea to FrankiFlow","body_de":"","body_en":""},
    {"heading_de":"Wo Service auf Technologie trifft","heading_en":"Where Service Meets Technology","body_de":"","body_en":""},
    {"heading_de":"Unsere Vision","heading_en":"Our Vision","body_de":"","body_en":""}
  ]$about$::jsonb;
